frequency:
  dct: false
  dft: false
  haar: false
imagePath: sample
matrixPath: null
spatial:
  avg: false
  gaussian: false
  laplace: false
  max: true
  median: false
  min: true
  prewitt: false
  sobel: false
