frequency:
  dct: false
  dft: false
  haar: false
imagePath: \Users\
matrixPath: sample
spatial:
  avg: true
  gaussian: false
  laplace: false
  max: true
  median: false
  min: true
  prewitt: false
  sobel: false
