#Configuration File

imagePath : null
matrixPath : null
domain:
      s: False #Spatial Domain 
      f: False #Frequency Domain
spatial :
      laplace :  False    #Laplacian Filter
      sobel :    False    #Sobel Filter
      prewitt :  False    #Prewitt Filter
      gaussian : False    #Gaussian Filter
      avg :      False    # Mean Filter
      max:       False    #Max Filter 
      min :      False    #Min Filter
      median :   False    #Mediam Filter


