frequency:
  dct: false
  dft: false
  haar: false
imagePath: C:\Users\ACER\Desktop\dip-cli\sample.png
matrixPath: null
spatial:
  avg: false
  gaussian: false
  laplacian: true
  max: false
  median: false
  min: false
  prewitt: false
  sobel: false
