frequency:
  butterworth: true
  d: '20'
  dct: false
  dft: false
  gaussian: false
  haar: false
  ideal: false
  n: '1.4'
  start: false
height: 300
path: C:\Users\ACER\Desktop\dip-cli\samples\sample.png
save: false
spatial:
  avg: false
  gaussian: false
  laplacian: false
  max: false
  median: false
  min: false
  mode: false
  prewitt: false
  sobel: false
type: image
width: 300
