frequency:
  butterworth: false
  dct: false
  dft: false
  gaussian: false
  haar: false
  ideal: false
  start: false
height: 300
path: C:\Users\ACER\Desktop\dip-cli\images\sample.png
spatial:
  avg: false
  gaussian: false
  laplacian: false
  max: true
  median: false
  min: false
  mode: false
  prewitt: false
  sobel: false
type: image
width: 300
