#Configuration File
path: null
type: null
height: null
width: null
spatial :
      laplacian :  False  #Laplacian Filter
      sobel :    False    #Sobel Filter
      prewitt :  False    #Prewitt Filter
      gaussian : False    #Gaussian Filter
      avg :      False    #Mean Filter
      max:       False    #Max Filter 
      min :      False    #Min Filter
      median :   False    #Median Filter
      mode : False
     

frequency :
      dft : False #Discrete Fourier Transform
      dct : False #Discrete Cosine Transform
      haar: False #Haar Transform
      start: False
      butterworth : False
      gaussian : False
      ideal : False

save: False
      


