frequency:
  butterworth: false
  dct: false
  dft: false
  gaussian: false
  haar: false
  ideal: false
  start: false
height: 300
path: C:\Users\ACER\Desktop\dip-cli\samples\sample.png
save: true
spatial:
  avg: false
  gaussian: false
  laplacian: false
  max: false
  median: false
  min: false
  mode: false
  prewitt: false
  sobel: true
type: image
width: 300
