frequency:
  butterworth: false
  d: 20
  dct: false
  dft: false
  gaussian: false
  ideal: false
  n: 1.2
  start: false
height: 300
path: C:\Users\ACER\Desktop\dip-cli\samples\image1.jpg
save: false
spatial:
  gaussian: false
  laplacian: false
  max: false
  mean: false
  median: false
  min: false
  prewitt: false
  sobel: true
type: image
width: 300
