#Configuration File
path: null
type: null
height: null
width: null
spatial :
      laplacian :  False  #Laplacian Filter
      sobel :    False    #Sobel Filter
      prewitt :  False    #Prewitt Filter
      gaussian : False    #Gaussian Filter
      mean :      False    #Mean Filter
      max:       False    #Max Filter 
      min :      False    #Min Filter
      median :   False    #Median Filter
      
     

frequency :
      dft : False #Discrete Fourier Transform
      dct : False #Discrete Cosine Transform
      start: False
      butterworth : False
      gaussian : False
      ideal : False
      d: 20
      n : 1.2

save: False
      


