frequency:
  butterworth: false
  dct: false
  dft: false
  gaussian: true
  haar: false
  ideal: false
  start: false
height: 3
path: C:\Users\ACER\Desktop\dip-cli\test.txt
spatial:
  avg: false
  gaussian: false
  laplacian: false
  max: false
  median: false
  min: false
  mode: false
  prewitt: false
  sobel: false
type: text
width: 3
