#Configuration File

path: null
type: null
spatial :
      laplacian :  False    #Laplacian Filter
      sobel :    False    #Sobel Filter
      prewitt :  False    #Prewitt Filter
      gaussian : False    #Gaussian Filter
      avg :      False    #Mean Filter
      max:       False    #Max Filter 
      min :      False    #Min Filter
      median :   False    #Mediam Filter

frequency :
      dft : False #Discrete Fourier Transform
      dct : False #Discrete Cosine Transform
      haar: False #Haar Transform


