frequency:
  dct: false
  dft: false
  haar: false
path: C:\Users\ACER\Desktop\dip-cli\test.txt
spatial:
  avg: false
  gaussian: false
  laplacian: true
  max: false
  median: false
  min: false
  prewitt: false
  sobel: false
type: text
